import { createInitialProjection, documentSchema, type Projection } from "@koi/core";

export function createWelcomeProjection(): Projection {
  const document = documentSchema.parse({
    schemaVersion: 1,
    id: "welcome-document",
    workspaceId: "local-workspace",
    name: "Welcome to Koi",
    revision: 0,
    historyId: "welcome-history",
    designProfile: { id: "koi.astryx", version: "0.5.0", tokens: {} },
    assets: [],
    pages: [
      {
        schemaVersion: 1,
        id: "page-explorations",
        name: "Explorations",
        elements: [
          {
            schemaVersion: 1,
            id: "frame-brief",
            kind: "frame",
            name: "1 · Product brief",
            version: 1,
            parentId: null,
            geometry: { x: 0, y: 0, width: 520, height: 660, rotation: 0 },
            properties: { clipContent: true, background: "#ffffff" },
          },
          {
            schemaVersion: 1,
            id: "brief-title",
            kind: "text",
            version: 1,
            parentId: "frame-brief",
            geometry: { x: 44, y: 52, width: 420, height: 96, rotation: 0 },
            properties: {
              content: "Design together, without the lock-in.",
              style: { fontSize: 32, fontWeight: 720, color: "#172035" },
            },
          },
          {
            schemaVersion: 1,
            id: "brief-body",
            kind: "text",
            version: 1,
            parentId: "frame-brief",
            geometry: { x: 44, y: 170, width: 420, height: 100, rotation: 0 },
            properties: {
              content:
                "Koi is a portable, HTML-native canvas where people and agents work on the same semantic document.",
              style: { fontSize: 17, color: "#5b6479" },
            },
          },
          {
            schemaVersion: 1,
            id: "brief-card",
            kind: "component",
            name: "Design principle",
            version: 1,
            parentId: "frame-brief",
            geometry: { x: 44, y: 292, width: 420, height: 190, rotation: 0 },
            properties: {
              profile: "koi.astryx",
              profileVersion: "0.5.0",
              componentId: "astryx.card",
              props: {
                title: "Native by construction",
                body: "Every component remains real HTML and CSS, ready to inspect, edit, and export.",
                variant: "blue",
                elevation: "low",
              },
            },
          },
          {
            schemaVersion: 1,
            id: "brief-note",
            kind: "note",
            version: 1,
            parentId: "frame-brief",
            geometry: { x: 44, y: 518, width: 250, height: 102, rotation: 0 },
            properties: { content: "Double-click text or notes to edit them.", color: "#ffe694" },
          },
          {
            schemaVersion: 1,
            id: "frame-components",
            kind: "frame",
            name: "2 · Astryx components",
            version: 1,
            parentId: null,
            geometry: { x: 590, y: 0, width: 560, height: 660, rotation: 0 },
            properties: { clipContent: true, background: "#ffffff" },
          },
          {
            schemaVersion: 1,
            id: "components-title",
            kind: "text",
            version: 1,
            parentId: "frame-components",
            geometry: { x: 40, y: 44, width: 470, height: 45, rotation: 0 },
            properties: {
              content: "Trusted design-system instances",
              style: { fontSize: 25, fontWeight: 700, color: "#172035" },
            },
          },
          {
            schemaVersion: 1,
            id: "component-banner",
            kind: "component",
            name: "Agent banner",
            version: 1,
            parentId: "frame-components",
            geometry: { x: 40, y: 120, width: 470, height: 120, rotation: 0 },
            properties: {
              profile: "koi.astryx",
              profileVersion: "0.5.0",
              componentId: "astryx.banner",
              props: {
                title: "Agent exploration ready",
                description: "Review this branch before making it the chosen direction.",
                status: "info",
              },
            },
          },
          {
            schemaVersion: 1,
            id: "component-input",
            kind: "component",
            name: "Project input",
            version: 1,
            parentId: "frame-components",
            geometry: { x: 40, y: 286, width: 310, height: 76, rotation: 0 },
            properties: {
              profile: "koi.astryx",
              profileVersion: "0.5.0",
              componentId: "astryx.text-input",
              props: { label: "Project", value: "Koi launch", size: "md" },
            },
          },
          {
            schemaVersion: 1,
            id: "component-button",
            kind: "component",
            name: "Primary action",
            version: 1,
            parentId: "frame-components",
            geometry: { x: 40, y: 407, width: 150, height: 44, rotation: 0 },
            properties: {
              profile: "koi.astryx",
              profileVersion: "0.5.0",
              componentId: "astryx.button",
              props: { label: "Create project", variant: "primary", size: "md" },
            },
          },
          {
            schemaVersion: 1,
            id: "component-badge",
            kind: "component",
            name: "Status",
            version: 1,
            parentId: "frame-components",
            geometry: { x: 220, y: 413, width: 110, height: 34, rotation: 0 },
            properties: {
              profile: "koi.astryx",
              profileVersion: "0.5.0",
              componentId: "astryx.badge",
              props: { label: "Human + agent", variant: "purple" },
            },
          },
          {
            schemaVersion: 1,
            id: "frame-flow",
            kind: "frame",
            name: "3 · Collaboration flow",
            version: 1,
            parentId: null,
            geometry: { x: 1220, y: 0, width: 620, height: 660, rotation: 0 },
            properties: { clipContent: true, background: "#fbfcff" },
          },
          {
            schemaVersion: 1,
            id: "flow-human",
            kind: "shape",
            version: 1,
            parentId: "frame-flow",
            geometry: { x: 58, y: 154, width: 190, height: 104, rotation: 0 },
            properties: {
              shape: "rectangle",
              fill: "#edf1ff",
              stroke: "#4d70e8",
              strokeWidth: 2,
            },
          },
          {
            schemaVersion: 1,
            id: "flow-agent",
            kind: "shape",
            version: 1,
            parentId: "frame-flow",
            geometry: { x: 370, y: 154, width: 190, height: 104, rotation: 0 },
            properties: {
              shape: "rectangle",
              fill: "#f2ebff",
              stroke: "#8056d8",
              strokeWidth: 2,
            },
          },
          {
            schemaVersion: 1,
            id: "flow-human-label",
            kind: "text",
            version: 1,
            parentId: "frame-flow",
            geometry: { x: 92, y: 188, width: 120, height: 38, rotation: 0 },
            properties: { content: "Human intent", style: { fontSize: 17, fontWeight: 650 } },
          },
          {
            schemaVersion: 1,
            id: "flow-agent-label",
            kind: "text",
            version: 1,
            parentId: "frame-flow",
            geometry: { x: 410, y: 188, width: 120, height: 38, rotation: 0 },
            properties: { content: "Agent command", style: { fontSize: 17, fontWeight: 650 } },
          },
          {
            schemaVersion: 1,
            id: "flow-connector",
            kind: "connector",
            version: 1,
            parentId: null,
            geometry: { x: 0, y: 0, width: 0, height: 0, rotation: 0 },
            properties: {
              from: { elementId: "flow-human", anchor: "right" },
              to: { elementId: "flow-agent", anchor: "left" },
              route: "bezier",
              points: [],
              stroke: "#6f7890",
              strokeWidth: 2,
            },
          },
          {
            schemaVersion: 1,
            id: "flow-explanation",
            kind: "text",
            version: 1,
            parentId: "frame-flow",
            geometry: { x: 58, y: 330, width: 500, height: 115, rotation: 0 },
            properties: {
              content:
                "Both surfaces commit the same bounded command. Stable IDs, versions, and visible history protect work from silent overwrites.",
              style: { fontSize: 18, color: "#596279", align: "center" },
            },
          },
          {
            schemaVersion: 1,
            id: "frame-gpu",
            kind: "frame",
            name: "4 · WebGPU leaf",
            version: 1,
            parentId: null,
            geometry: { x: 1910, y: 0, width: 520, height: 660, rotation: 0 },
            properties: { clipContent: true, background: "#10172a" },
          },
          {
            schemaVersion: 1,
            id: "gpu-title",
            kind: "text",
            version: 1,
            parentId: "frame-gpu",
            geometry: { x: 42, y: 42, width: 430, height: 54, rotation: 0 },
            properties: {
              content: "Programmable pixels, bounded.",
              style: { fontSize: 27, fontWeight: 720, color: "#ffffff" },
            },
          },
          {
            schemaVersion: 1,
            id: "gpu-shader",
            kind: "shader",
            version: 1,
            parentId: "frame-gpu",
            geometry: { x: 42, y: 132, width: 436, height: 330, rotation: 0 },
            properties: {
              shaderId: "koi.gradient-field",
              parameters: { speed: 0.4, colorA: "#63dbe6", colorB: "#7b5cff" },
              playbackSpeed: 1,
              deterministicFrame: 0,
              quality: 1,
            },
          },
          {
            schemaVersion: 1,
            id: "gpu-caption",
            kind: "text",
            version: 1,
            parentId: "frame-gpu",
            geometry: { x: 42, y: 504, width: 436, height: 100, rotation: 0 },
            properties: {
              content:
                "Koi-authored programmable GPU work uses WebGPU and WGSL. The editor remains useful without it.",
              style: { fontSize: 16, color: "#bac4e1" },
            },
          },
        ],
      },
    ],
  });
  return createInitialProjection(document);
}
