import { readFileSync } from "node:fs";

import { describe, expect, it } from "vite-plus/test";

import { buildTheme, runDesignMdCli, themeExportName, type CliIo } from "../src/index.js";

const apple = readFileSync(new URL("../fixtures/apple/DESIGN.md", import.meta.url), "utf8");
const koi = readFileSync(new URL("../../../DESIGN.md", import.meta.url), "utf8");

function memoryIo(files: Map<string, string>) {
  const out: string[] = [];
  const err: string[] = [];
  const io: CliIo = {
    readFile: async (path) => {
      const content = files.get(path);
      if (content === undefined) throw new Error(`ENOENT ${path}`);
      return content;
    },
    writeFile: async (path, content) => {
      files.set(path, content);
    },
    exists: async (path) => files.has(path),
    stdout: (line) => out.push(line),
    stderr: (line) => err.push(line),
  };
  return { io, out, err };
}

describe("emitThemeModule", () => {
  it("emits Koi's own DESIGN.md as a theme with no overrides", () => {
    const { module, bridge } = buildTheme(koi, { name: "koi", sourceLabel: "DESIGN.md" });
    expect(bridge.theme.tokens).toEqual({});
    expect(module).toBe(
      [
        "// @generated by @koidesign/design-md from DESIGN.md. Do not edit; change the DESIGN.md and rebuild.",
        "// DESIGN.md format alpha · Astryx profile koi.astryx/0.5.0",
        'import { defineTheme } from "@astryxdesign/core/theme";',
        "",
        "export const koiTheme = defineTheme({",
        '  "name": "koi"',
        "});",
        "",
      ].join("\n"),
    );
  });

  it("is deterministic and names the export after the theme", () => {
    const first = buildTheme(apple, { name: "apple" }).module;
    const second = buildTheme(apple, { name: "apple" }).module;
    expect(first).toBe(second);
    expect(first).toContain("export const appleTheme = defineTheme({");
    expect(first).toContain('"accent": [\n      "#0066cc",\n      "#2997ff"\n    ]');
    expect(themeExportName("Apple-design-analysis")).toBe("appleDesignAnalysisTheme");
  });
});

describe("koi-design-md CLI", () => {
  it("builds, then verifies with --check, and fails the check on drift", async () => {
    const files = new Map([["DESIGN.md", apple]]);
    const { io, out, err } = memoryIo(files);
    expect(
      await runDesignMdCli(
        ["build", "DESIGN.md", "--out", "apple.theme.ts", "--name", "apple"],
        io,
      ),
    ).toBe(0);
    expect(files.get("apple.theme.ts")).toContain("appleTheme");
    expect(out.at(-1)).toBe("✓ apple.theme.ts");
    expect(
      await runDesignMdCli(
        ["build", "DESIGN.md", "--out", "apple.theme.ts", "--name", "apple", "--check"],
        io,
      ),
    ).toBe(0);
    files.set("apple.theme.ts", "stale");
    expect(
      await runDesignMdCli(
        ["build", "DESIGN.md", "--out", "apple.theme.ts", "--name", "apple", "--check"],
        io,
      ),
    ).toBe(1);
    expect(err.at(-1)).toMatch(/out of date/);
  });

  it("inspects coverage as text or JSON", async () => {
    const files = new Map([["DESIGN.md", apple]]);
    const { io, out } = memoryIo(files);
    expect(await runDesignMdCli(["inspect", "DESIGN.md"], io)).toBe(0);
    expect(out.join("\n")).toContain("colors.primary → color.accent");
    out.length = 0;
    expect(await runDesignMdCli(["inspect", "DESIGN.md", "--json"], io)).toBe(0);
    const report = JSON.parse(out.join("\n")) as { profile: { name: string } };
    expect(report.profile.name).toBe("Apple-design-analysis");
  });

  it("explains usage errors without throwing", async () => {
    const { io, err } = memoryIo(new Map([["DESIGN.md", apple]]));
    expect(await runDesignMdCli([], io)).toBe(2);
    expect(await runDesignMdCli(["build", "DESIGN.md"], io)).toBe(2);
    expect(await runDesignMdCli(["build", "missing.md", "--out", "x.ts"], io)).toBe(2);
    expect(await runDesignMdCli(["frobnicate", "DESIGN.md"], io)).toBe(2);
    expect(err.some((line) => line.includes("--out"))).toBe(true);
    const bad = memoryIo(new Map([["DESIGN.md", "# nope\n"]]));
    expect(await runDesignMdCli(["build", "DESIGN.md", "--out", "x.ts"], bad.io)).toBe(1);
  });
});
