import type { AstryxBridgeResult, AstryxThemeSpec } from "./astryx.js";

export interface EmitOptions {
  /** Name of the exported constant; defaults to `<name>Theme` in camel case. */
  exportName?: string;
  /** Where the DESIGN.md came from, for the generated header. */
  sourceLabel?: string;
}

export function themeExportName(name: string): string {
  const camel = name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, index) =>
      index === 0 ? part.toLowerCase() : part[0]!.toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join("");
  return `${camel || "design"}Theme`;
}

/** Only the theme fields that carry values, so an unstyled design emits `{ name }` alone. */
export function themeInput(theme: AstryxThemeSpec): Record<string, unknown> {
  const input: Record<string, unknown> = { name: theme.name };
  if (theme.color) input.color = theme.color;
  if (theme.typography && Object.keys(theme.typography).length > 0) {
    input.typography = theme.typography;
  }
  if (Object.keys(theme.tokens).length > 0) input.tokens = theme.tokens;
  if (Object.keys(theme.components).length > 0) input.components = theme.components;
  return input;
}

/**
 * Emit a TypeScript module that calls Astryx's `defineTheme`, ready for `astryx theme build`.
 * The output is deterministic for a given input so it can be committed and drift-checked.
 */
export function emitThemeModule(result: AstryxBridgeResult, options: EmitOptions = {}): string {
  const exportName = options.exportName ?? themeExportName(result.theme.name);
  const source = options.sourceLabel ?? "DESIGN.md";
  const literal = JSON.stringify(themeInput(result.theme), null, 2);
  return [
    `// @generated by @koidesign/design-md from ${source}. Do not edit; change the DESIGN.md and rebuild.`,
    `// DESIGN.md format ${result.formatVersion} · Astryx profile ${result.profile.id}/${result.profile.version}`,
    `import { defineTheme } from "@astryxdesign/core/theme";`,
    ``,
    `export const ${exportName} = defineTheme(${literal});`,
    ``,
  ].join("\n");
}
