import {
  colorVars,
  fontWeightVars,
  radiusVars,
  shadowVars,
  textSizeVars,
  typographyVars,
} from "@astryxdesign/core/theme/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

const hoverable = "@media (hover: hover)";

/**
 * Styles for Koi's spatial canvas: the one surface Astryx has no components for. Every value is an
 * Astryx token so the canvas follows the active theme; only geometry literals stay literal.
 */
export const canvasStyles = stylex.create({
  root: {
    backgroundColor: colorVars["--color-background-body"],
    height: "100%",
    isolation: "isolate",
    minHeight: 0,
    outlineStyle: "none",
    overflow: "hidden",
    position: "relative",
    touchAction: "none",
  },
  keyboardFocus: {
    boxShadow: {
      default: "none",
      ":focus-visible": `inset 0 0 0 2px ${colorVars["--color-accent"]}`,
    },
  },
  hand: {
    cursor: { default: "grab", ":active": "grabbing" },
  },
  pen: {
    cursor: "crosshair",
  },
  empty: {
    alignItems: "center",
    color: colorVars["--color-text-secondary"],
    display: "flex",
    height: "100%",
    justifyContent: "center",
  },
  grid: {
    backgroundImage: `radial-gradient(circle, ${colorVars["--color-border-emphasized"]} 1px, transparent 1.4px)`,
    backgroundPosition: "12px 12px",
    backgroundSize: "24px 24px",
    inset: 0,
    pointerEvents: "none",
    position: "absolute",
  },
  worldRoot: {
    height: 0,
    left: 0,
    position: "absolute",
    top: 0,
    transformOrigin: "0 0",
    width: 0,
  },
  layer: {
    height: 1,
    left: 0,
    overflow: "visible",
    position: "absolute",
    top: 0,
    width: 1,
  },
  domLayer: {
    zIndex: 1,
  },
  svgLayer: {
    zIndex: 2,
  },
  element: {
    position: "absolute",
    transformOrigin: "center",
    userSelect: "none",
  },
  hoverable: {
    outlineColor: {
      default: "transparent",
      [hoverable]: { default: "transparent", ":hover": colorVars["--color-accent-muted"] },
    },
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: 1.5,
  },
  selected: {
    outlineColor: colorVars["--color-accent"],
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: 1.5,
  },
  frame: {
    contain: "layout style",
  },
  frameSurface: {
    backgroundColor: colorVars["--color-background-surface"],
    borderRadius: radiusVars["--radius-none"],
    boxShadow: shadowVars["--shadow-low"],
    height: "100%",
    width: "100%",
  },
  frameLabel: {
    color: colorVars["--color-text-secondary"],
    fontFamily: typographyVars["--font-family-body"],
    fontSize: textSizeVars["--font-size-sm"],
    fontWeight: fontWeightVars["--font-weight-semibold"],
    left: 0,
    lineHeight: "20px",
    position: "absolute",
    top: -24,
    whiteSpace: "nowrap",
  },
  frameLabelSelected: {
    color: colorVars["--color-accent"],
  },
  frameChildren: {
    inset: 0,
    position: "absolute",
  },
  fill: {
    height: "100%",
    width: "100%",
  },
  componentSurface: {
    alignItems: "stretch",
    display: "flex",
    justifyContent: "stretch",
  },
  textSurface: {
    overflow: "hidden",
    whiteSpace: "pre-wrap",
  },
  noteSurface: {
    borderRadius: radiusVars["--radius-none"],
    boxShadow: shadowVars["--shadow-low"],
    color: colorVars["--color-text-yellow"],
    fontFamily: typographyVars["--font-family-body"],
    fontSize: 16,
    lineHeight: 1.45,
    overflow: "hidden",
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
    position: "relative",
    whiteSpace: "pre-wrap",
    "::after": {
      borderColor: "transparent transparent rgb(255 255 255 / 55%) rgb(0 0 0 / 7%)",
      borderStyle: "solid",
      borderWidth: "0 0 14px 14px",
      bottom: 0,
      content: '""',
      position: "absolute",
      right: 0,
    },
  },
  imageSurface: {
    display: "block",
  },
  shaderSurface: {
    alignContent: "center",
    backgroundColor: "#17203a",
    backgroundImage:
      "radial-gradient(circle at 22% 18%, #63dbe6 0, transparent 34%), radial-gradient(circle at 78% 72%, #7b5cff 0, transparent 38%)",
    borderRadius: radiusVars["--radius-inner"],
    color: "#fff",
    display: "grid",
    gap: 5,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  shaderMeta: {
    opacity: 0.72,
  },
  missingSurface: {
    alignItems: "center",
    backgroundColor: colorVars["--color-background-muted"],
    color: colorVars["--color-text-secondary"],
    display: "flex",
    justifyContent: "center",
  },
  svgSelected: {
    filter: `drop-shadow(0 0 2px ${colorVars["--color-accent"]})`,
    stroke: colorVars["--color-accent"],
  },
  overlay: {
    height: "100%",
    inset: 0,
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 10,
  },
  selectionOverlay: {
    borderColor: colorVars["--color-accent"],
    borderRadius: radiusVars["--radius-none"],
    borderStyle: "solid",
    borderWidth: 1.5,
    boxShadow: `0 0 0 1px ${colorVars["--color-background-surface"]}`,
    left: 0,
    pointerEvents: "none",
    position: "absolute",
    top: 0,
  },
  resizeHandle: {
    backgroundColor: colorVars["--color-background-surface"],
    borderColor: colorVars["--color-accent"],
    borderRadius: radiusVars["--radius-inner"],
    borderStyle: "solid",
    borderWidth: 1.5,
    bottom: -6,
    boxShadow: shadowVars["--shadow-low"],
    cursor: "nwse-resize",
    height: 11,
    padding: 0,
    pointerEvents: "auto",
    position: "absolute",
    right: -6,
    width: 11,
  },
  textEditor: {
    backgroundColor: colorVars["--color-background-surface"],
    borderColor: colorVars["--color-accent"],
    borderRadius: radiusVars["--radius-inner"],
    borderStyle: "solid",
    borderWidth: 1.5,
    boxShadow: shadowVars["--shadow-med"],
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    left: 0,
    lineHeight: 1.45,
    outlineStyle: "none",
    padding: 10,
    pointerEvents: "auto",
    position: "absolute",
    resize: "none",
    top: 0,
  },
  meta: {
    alignItems: "center",
    backgroundColor: colorVars["--color-background-surface"],
    borderColor: colorVars["--color-border-emphasized"],
    borderRadius: radiusVars["--radius-full"],
    borderStyle: "solid",
    borderWidth: 1,
    bottom: 12,
    boxShadow: shadowVars["--shadow-med"],
    color: colorVars["--color-text-secondary"],
    display: "flex",
    fontFamily: typographyVars["--font-family-body"],
    fontSize: textSizeVars["--font-size-sm"],
    fontWeight: fontWeightVars["--font-weight-medium"],
    pointerEvents: "none",
    position: "absolute",
    right: 12,
    zIndex: 12,
  },
  metaItem: {
    paddingBottom: 6,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 6,
  },
  metaDivided: {
    borderLeftColor: colorVars["--color-border"],
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
  },
  metaZoom: {
    color: colorVars["--color-text-primary"],
    fontVariantNumeric: "tabular-nums",
  },
});
